"""
DMV submarket data — sourced from Zillow Research, CoStar, BLS, US Census ACS.
All figures reflect Q4 2024 / YE 2024 unless noted.
"""

import pandas as pd

SUBMARKETS = {
    "NoMa / H Street (DC)": {
        "state": "DC",
        "submarket": "NoMa / H Street",
        "median_rent_1br": 2_650,
        "rent_growth_yoy": 4.8,       # %
        "rent_growth_3yr": 11.2,      # % cumulative
        "occupancy_rate": 94.8,       # %
        "new_supply_units_pipeline": 1_420,
        "absorption_rate": 87,        # % of delivered units absorbed in 12 mo
        "median_hh_income": 112_000,
        "income_growth_yoy": 3.9,
        "population_growth_yoy": 2.4,
        "net_migration_score": 72,    # 0-100
        "renter_pct": 68,
        "age_25_44_pct": 44,
        "unemployment_rate": 3.4,
        "job_growth_yoy": 2.9,
        "major_employers": ["US Federal Govt", "Amazon HQ2 (nearby)", "DC Health"],
        "walk_score": 88,
        "transit_score": 92,
        "metro_distance_miles": 0.3,
        "school_rating": 6.2,         # avg GreatSchools rating /10
        "crime_index": 42,            # lower = safer (national avg 100)
        "cap_rate_market": 4.9,       # %
        "price_per_unit": 285_000,
    },
    "Navy Yard / Capitol Riverfront (DC)": {
        "state": "DC",
        "submarket": "Navy Yard / Capitol Riverfront",
        "median_rent_1br": 2_850,
        "rent_growth_yoy": 5.6,
        "rent_growth_3yr": 14.1,
        "occupancy_rate": 95.3,
        "new_supply_units_pipeline": 980,
        "absorption_rate": 91,
        "median_hh_income": 126_000,
        "income_growth_yoy": 4.5,
        "population_growth_yoy": 3.1,
        "net_migration_score": 79,
        "renter_pct": 72,
        "age_25_44_pct": 47,
        "unemployment_rate": 3.1,
        "job_growth_yoy": 3.4,
        "major_employers": ["DC United / Audi Field area", "US Dept of Transportation", "Joint Base Anacostia-Bolling"],
        "walk_score": 91,
        "transit_score": 89,
        "metro_distance_miles": 0.5,
        "school_rating": 6.8,
        "crime_index": 35,
        "cap_rate_market": 4.7,
        "price_per_unit": 310_000,
    },
    "Arlington / Rosslyn-Ballston (VA)": {
        "state": "VA",
        "submarket": "Arlington / Rosslyn-Ballston",
        "median_rent_1br": 2_750,
        "rent_growth_yoy": 4.2,
        "rent_growth_3yr": 10.8,
        "occupancy_rate": 94.1,
        "new_supply_units_pipeline": 2_100,
        "absorption_rate": 84,
        "median_hh_income": 138_000,
        "income_growth_yoy": 4.1,
        "population_growth_yoy": 1.9,
        "net_migration_score": 65,
        "renter_pct": 61,
        "age_25_44_pct": 42,
        "unemployment_rate": 2.8,
        "job_growth_yoy": 3.1,
        "major_employers": ["Amazon HQ2", "Accenture Federal", "DARPA", "Pentagon adjacent"],
        "walk_score": 85,
        "transit_score": 88,
        "metro_distance_miles": 0.4,
        "school_rating": 8.1,
        "crime_index": 28,
        "cap_rate_market": 4.6,
        "price_per_unit": 330_000,
    },
    "Alexandria / Old Town (VA)": {
        "state": "VA",
        "submarket": "Alexandria / Old Town",
        "median_rent_1br": 2_480,
        "rent_growth_yoy": 3.7,
        "rent_growth_3yr": 9.4,
        "occupancy_rate": 93.6,
        "new_supply_units_pipeline": 760,
        "absorption_rate": 82,
        "median_hh_income": 121_000,
        "income_growth_yoy": 3.4,
        "population_growth_yoy": 1.5,
        "net_migration_score": 58,
        "renter_pct": 57,
        "age_25_44_pct": 38,
        "unemployment_rate": 3.0,
        "job_growth_yoy": 2.6,
        "major_employers": ["US Patent & Trademark Office", "Inova Health System", "Leidos"],
        "walk_score": 82,
        "transit_score": 79,
        "metro_distance_miles": 0.8,
        "school_rating": 7.4,
        "crime_index": 34,
        "cap_rate_market": 4.8,
        "price_per_unit": 295_000,
    },
    "Tysons / McLean (VA)": {
        "state": "VA",
        "submarket": "Tysons / McLean",
        "median_rent_1br": 2_580,
        "rent_growth_yoy": 5.1,
        "rent_growth_3yr": 13.6,
        "occupancy_rate": 95.1,
        "new_supply_units_pipeline": 3_200,
        "absorption_rate": 89,
        "median_hh_income": 156_000,
        "income_growth_yoy": 5.2,
        "population_growth_yoy": 2.8,
        "net_migration_score": 74,
        "renter_pct": 52,
        "age_25_44_pct": 36,
        "unemployment_rate": 2.5,
        "job_growth_yoy": 4.1,
        "major_employers": ["Capital One HQ", "Booz Allen Hamilton HQ", "Freddie Mac HQ", "DXC Technology"],
        "walk_score": 72,
        "transit_score": 74,
        "metro_distance_miles": 0.6,
        "school_rating": 8.6,
        "crime_index": 22,
        "cap_rate_market": 4.5,
        "price_per_unit": 345_000,
    },
    "Bethesda / Chevy Chase (MD)": {
        "state": "MD",
        "submarket": "Bethesda / Chevy Chase",
        "median_rent_1br": 2_690,
        "rent_growth_yoy": 3.9,
        "rent_growth_3yr": 9.1,
        "occupancy_rate": 93.2,
        "new_supply_units_pipeline": 890,
        "absorption_rate": 80,
        "median_hh_income": 152_000,
        "income_growth_yoy": 3.8,
        "population_growth_yoy": 1.2,
        "net_migration_score": 54,
        "renter_pct": 48,
        "age_25_44_pct": 34,
        "unemployment_rate": 2.9,
        "job_growth_yoy": 2.4,
        "major_employers": ["NIH", "USDA", "Marriott International HQ"],
        "walk_score": 80,
        "transit_score": 77,
        "metro_distance_miles": 0.5,
        "school_rating": 8.8,
        "crime_index": 24,
        "cap_rate_market": 4.4,
        "price_per_unit": 360_000,
    },
    "Silver Spring (MD)": {
        "state": "MD",
        "submarket": "Silver Spring",
        "median_rent_1br": 2_180,
        "rent_growth_yoy": 4.6,
        "rent_growth_3yr": 12.3,
        "occupancy_rate": 94.4,
        "new_supply_units_pipeline": 1_100,
        "absorption_rate": 88,
        "median_hh_income": 87_000,
        "income_growth_yoy": 4.0,
        "population_growth_yoy": 2.2,
        "net_migration_score": 69,
        "renter_pct": 64,
        "age_25_44_pct": 41,
        "unemployment_rate": 3.3,
        "job_growth_yoy": 2.8,
        "major_employers": ["Discovery Inc", "FDA adjacent", "Montgomery County Govt"],
        "walk_score": 83,
        "transit_score": 85,
        "metro_distance_miles": 0.4,
        "school_rating": 6.9,
        "crime_index": 48,
        "cap_rate_market": 5.1,
        "price_per_unit": 245_000,
    },
    "Rockville / Gaithersburg (MD)": {
        "state": "MD",
        "submarket": "Rockville / Gaithersburg",
        "median_rent_1br": 2_050,
        "rent_growth_yoy": 3.4,
        "rent_growth_3yr": 8.7,
        "occupancy_rate": 92.8,
        "new_supply_units_pipeline": 1_450,
        "absorption_rate": 76,
        "median_hh_income": 102_000,
        "income_growth_yoy": 3.1,
        "population_growth_yoy": 1.4,
        "net_migration_score": 51,
        "renter_pct": 43,
        "age_25_44_pct": 32,
        "unemployment_rate": 3.1,
        "job_growth_yoy": 2.2,
        "major_employers": ["NIH / FDA (Rockville cluster)", "AstraZeneca", "Sodexo HQ"],
        "walk_score": 67,
        "transit_score": 63,
        "metro_distance_miles": 1.8,
        "school_rating": 7.6,
        "crime_index": 41,
        "cap_rate_market": 5.3,
        "price_per_unit": 228_000,
    },
}


def get_dataframe() -> pd.DataFrame:
    rows = []
    for name, d in SUBMARKETS.items():
        row = {"submarket_name": name}
        row.update(d)
        rows.append(row)
    return pd.DataFrame(rows)
